### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Masynchin** [objectionary/news.eolang.org#5]
In [this article](https://news.eolang.org/2022-06-09-memory-enclosure.html) link to cage object is broken. There is two issues:

1) Current link leads to memory object, not cage.
2) Current link contains `/grey/` in URL. Cage was moved from `/grey/` folder in [0.23.11](https://github.com/objectionary/home/commit/f8b35878ff8725547bc131bff5ff038f19abff37), and memory never been in this folder.

**Comment by Graur** [comment]
@Masynchin Indeed, this link is broken. You are welcome to submit a pull request to solve this.
